project:
  type: book
  output-dir: docs   # needed for GitHub Pages later

book:
  title: "Time-Series Analysis of Paleoclimate Signals"
  subtitle: "Practical Workshop"
  author: 
    - "Anne-Christine Da Silva"
  date: today
  chapters:
    - workshop_coldigioco_Practical00_PreResquisite.qmd
    - workshop_coldigioco_Practical01_BasicR.qmd
    - workshop_coldigioco_Practical02_astrochron.qmd
    - workshop_coldigioco_Practical03_StratigrapheR_new.qmd
    - workshop_coldigioco_Practical04_WaverideR.qmd
    - workshop_coldigioco_Practical05_astrochron_advanced.qmd

format:
  html:
    toc: true
    number-sections: true
    code-fold: true
    theme: cosmo
